// jtsftm_game_sdram.v is automatically generated by JTFRAME
// Do not modify it
// Do not add it to git

`ifndef JTFRAME_COLORW
`define JTFRAME_COLORW 4
`endif

`ifndef JTFRAME_BUTTONS
`define JTFRAME_BUTTONS 2
`endif

module jtsftm_game_sdram(
    `include "jtframe_common_ports.inc"
    `include "jtframe_mem_ports.inc"
);

/* verilator lint_off WIDTH */
localparam [25:0] BA1_START  =`ifdef JTFRAME_BA1_START  `JTFRAME_BA1_START  `else 26'd0 `endif;
localparam [25:0] BA2_START  =`ifdef JTFRAME_BA2_START  `JTFRAME_BA2_START  `else 26'd0 `endif;
localparam [25:0] BA3_START  =`ifdef JTFRAME_BA3_START  `JTFRAME_BA3_START  `else 26'd0 `endif;
localparam [25:0] PROM_START =`ifdef JTFRAME_PROM_START `JTFRAME_PROM_START `else 26'd0 `endif;
localparam [25:0] HEADER_LEN =`ifdef JTFRAME_HEADER     `JTFRAME_HEADER     `else 26'd0 `endif;
localparam        SDRAMW     =`ifdef JTFRAME_SDRAM_XL 25 `elsif JTFRAME_SDRAM_LARGE 24 `else 23 `endif;
localparam        IOCTL_AW   =`ifdef JTFRAME_SDRAM_XL 27 `else 26 `endif;
/* verilator lint_on WIDTH */



// Audio channels 
wire mute;
// Additional ports

// BRAM buses
// SDRAM buses

wire [19:2] main_addr;
wire [31:0] main_data;
wire        main_cs, main_ok;
wire [17:0] snd_addr;
wire [ 7:0] snd_data;
wire        snd_cs, snd_ok;
wire [21:1] srom_addr;
wire [15:0] srom_data;
wire        srom_cs, srom_ok;
wire [24:1] grom_addr;
wire [15:0] grom_data;
wire        grom_cs, grom_ok;
wire [18:1] grm3_addr;
wire [15:0] grm3_data;
wire        grm3_cs, grm3_ok;
wire [20:1] vram_addr;
wire [15:0] vram_data;
wire        vram_cs, vram_ok;
wire        vram_we;
wire [15:0] vram_din;
wire [ 1:0] vram_dsn;

wire        prom_we, header;
wire [SDRAMW-2:0] raw_addr, post_addr;
wire [SDRAMW-2:0] ioctl_prog_addr   = ioctl_addr[SDRAMW-2:0];
wire [IOCTL_AW-1:0] pre_addr, dwnld_addr, ioctl_addr_noheader;
wire [ 7:0] post_data;
wire [15:0] raw_data;
wire [ 7:0] pcb_id;
wire        pass_io;
// Clock enable signals
wire e020_cen; 
wire es_cen; 
wire snd_cen; 
wire gfx4_en, gfx8_en, gfx16_en, gfx16b_en, gfx16c_en, ioctl_dwn;

assign pass_io = header | ioctl_ram;
assign ioctl_addr_noheader = `ifdef JTFRAME_HEADER header ? ioctl_addr : ioctl_addr - HEADER_LEN `else ioctl_addr `endif ;
`ifdef JTFRAME_SDRAM_CACHE
assign burst_addr = { (SDRAMW-1){1'b0} };
assign burst_ba   = 2'd0;
assign burst_rd   = 1'b0;
assign burst_wr   = 1'b0;
assign burst_din  = 16'd0;
`endif

wire rst_h, rst24_h, rst48_h, hold_rst;

/* verilator tracing_off */
jtframe_rsthold u_hold(
    .rst    ( rst       ),
    .clk    ( clk       ),
    .hold   ( hold_rst  ),
    .rst_h  ( rst_h     ),
    .rst24  ( rst24     ),
    .clk24  ( clk24     ),
    .rst24_h( rst24_h   )
`ifdef JTFRAME_CLK48 ,
    .rst48  ( rst48     ),
    .clk48  ( clk48     ),
    .rst48_h( rst48_h   )
`endif
);
/* verilator tracing_on */
jtsftm_game u_game(
    .rst        ( rst_h     ),
    .clk        ( clk       ),
    .rst24      ( rst24_h   ),
    .clk24      ( clk24     ),
`ifdef JTFRAME_CLK48
    .rst48      ( rst48_h   ),
    .clk48      ( clk48     ),
`endif
    .rst96      ( rst96     ),
    .clk96      ( clk96     ),
    // Audio channels
    
    
    // Sound output
`ifdef JTFRAME_STEREO
    .snd_left       ( snd_left      ),
    .snd_right      ( snd_right     ),
`else
    .snd            ( snd           ),
`endif
    .sample         ( sample        ), 
    .snd_en         ( snd_en        ),
    .snd_vol        ( snd_vol       ),
    .e020_cen    ( e020_cen    ), 
    .es_cen    ( es_cen    ), 
    .snd_cen    ( snd_cen    ), 

    .pxl2_cen       ( pxl2_cen      ),
    .pxl_cen        ( pxl_cen       ),
    .red            ( red           ),
    .green          ( green         ),
    .blue           ( blue          ),
    .LHBL           ( LHBL          ),
    .LVBL           ( LVBL          ),
    .HS             ( HS            ),
    .VS             ( VS            ),
    // cabinet I/O
    .cab_1p   ( cab_1p  ),
    .coin     ( coin    ),
    .joystick1    ( joystick1        ), .joystick2    ( joystick2        ),
    .joystick3    ( joystick3        ), .joystick4    ( joystick4        ), `ifdef JTFRAME_MOUSE
    .mouse_1p     ( mouse_1p         ), .mouse_2p     ( mouse_2p         ), .mouse_strobe ( mouse_strobe ), `endif `ifdef JTFRAME_LIGHTGUN
    .gun_1p_x     ( gun_1p_x         ), .gun_1p_y     ( gun_1p_y         ),
    .gun_2p_x     ( gun_2p_x         ), .gun_2p_y     ( gun_2p_y         ), `endif `ifdef JTFRAME_SPINNER
    .spinner_1p   ( spinner_1p       ), .spinner_2p   ( spinner_2p       ), `endif
    .joyana_l1    ( joyana_l1        ), .joyana_l2    ( joyana_l2        ),
    .joyana_l3    ( joyana_l3        ), .joyana_l4    ( joyana_l4        ),
    .joyana_r1    ( joyana_r1        ), .joyana_r2    ( joyana_r2        ),
    .joyana_r3    ( joyana_r3        ), .joyana_r4    ( joyana_r4        ),
    .dial_x       ( dial_x           ), .dial_y       ( dial_y           ),
    // DIP switches
    .status         ( status        ),
    .dipsw          ( dipsw         ),
    .service        ( service       ),
    .tilt           ( tilt          ),
    .dip_pause      ( dip_pause     ),
    .dip_flip       ( dip_flip      ),
    .dip_test       ( dip_test      ),
    .dip_fxlevel    ( dip_fxlevel   ),
    // Ports declared in mem.yaml
    // Memory interface - SDRAM
    .main_addr ( main_addr ),
    .main_cs   ( main_cs   ),
    .main_ok   ( main_ok   ),
    .main_data ( main_data ),
    
    .snd_addr ( snd_addr ),
    .snd_cs   ( snd_cs   ),
    .snd_ok   ( snd_ok   ),
    .snd_data ( snd_data ),
    
    .srom_addr ( srom_addr ),
    .srom_cs   ( srom_cs   ),
    .srom_ok   ( srom_ok   ),
    .srom_data ( srom_data ),
    
    .grom_addr ( grom_addr ),
    .grom_cs   ( grom_cs   ),
    .grom_ok   ( grom_ok   ),
    .grom_data ( grom_data ),
    
    .grm3_addr ( grm3_addr ),
    .grm3_cs   ( grm3_cs   ),
    .grm3_ok   ( grm3_ok   ),
    .grm3_data ( grm3_data ),
    
    .vram_addr ( vram_addr ),
    .vram_cs   ( vram_cs   ),
    .vram_ok   ( vram_ok   ),
    .vram_data ( vram_data ),
    .vram_we   ( vram_we   ),
    .vram_dsn  ( vram_dsn  ),
    .vram_din  ( vram_din  ),
    
    // Memory interface - BRAM

`ifdef JTFRAME_SRAM
    // SRAM
    .sram_addr  ( sram_addr     ),
    .sram_din   ( sram_din      ),
    .sram_dout  ( sram_dout     ),
    .sram_wen   ( sram_wen      ),
    .sram_dsn   ( sram_dsn      ),
    .sram_ok    ( sram_ok       ),
`endif

`ifdef JTFRAME_SAVEGAME
    // Save/Load
    .sav_change ( sav_change    ),
    .sav_wait   ( sav_wait      ),
    .sav_done   ( sav_done      ),
    .sav_wr     ( sav_wr        ),
    .sav_ack    ( sav_ack       ),
    .sav_din    ( sav_din       ),
    .sav_dout   ( sav_dout      ),
    .sav_addr   ( sav_addr      ),
`endif
    // PROM writting
    .ioctl_addr   ( pass_io ? ioctl_addr       : ioctl_addr_noheader  ),
    .prog_addr    ( pass_io ? ioctl_prog_addr : raw_addr      ),
    .prog_data    ( pass_io ? ioctl_dout       : raw_data[7:0] ),
    .prog_we      ( pass_io ? ioctl_wr         : prog_we       ),
    .prog_ba      ( prog_ba        ), // prog_ba supplied in case it helps re-mapping addresses
    .prom_we      ( pass_io ? 1'b0 : prom_we ),
`ifdef JTFRAME_HEADER
    .header       ( header         ),
`endif
`ifdef JTFRAME_IOCTL_RD
    .ioctl_din    ( ioctl_din      ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ), `endif
    .ioctl_ram    ( ioctl_ram      ),
    .ioctl_cart   ( ioctl_cart     ),
    // Debug
    .debug_bus    ( debug_bus      ),
    .debug_view   ( debug_view     ),
`ifdef JTFRAME_STATUS
    .st_addr      ( st_addr        ),
    .st_dout      ( st_dout        ),
`endif
`ifdef JTFRAME_LF_BUFFER
    .game_vrender( game_vrender  ),
    .game_hdump  ( game_hdump    ),
    .ln_addr     ( ln_addr       ),
    .ln_data     ( ln_data       ),
    .ln_done     ( ln_done       ),
    .ln_hs       ( ln_hs         ),
    .ln_dout     ( ln_dout       ),
    .ln_pxl      ( ln_pxl        ),
    .ln_v        ( ln_v          ),
    .ln_vs       ( ln_vs         ),
    .ln_lvbl     ( ln_lvbl       ),
    .ln_we       ( ln_we         ),
    .fb_keep     ( fb_keep       ),
`ifdef JTFRAME_LF_ZOOM
    .h_step      ( h_step        ),
    .v_step      ( v_step        ),
`endif
`endif
    .gfx_en      ( gfx_en        )
);
/* verilator tracing_off */
assign dwnld_busy = ioctl_rom | prom_we; // prom_we is really just for sims
assign dwnld_addr = ioctl_addr;
`ifdef JTFRAME_SDRAM_XL
wire [26:0] dwnld_addr_wide = dwnld_addr;
`else
wire [26:0] dwnld_addr_wide = {1'b0,dwnld_addr};
`endif
assign prog_addr = raw_addr;
assign prog_data = raw_data;
assign gfx4_en   = 0;
assign gfx8_en   = 0;
assign gfx16_en  = 0;
assign gfx16b_en = 0;
assign gfx16c_en = 0;
assign ioctl_dwn = ioctl_rom | ioctl_cart;
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_dwnld #(
    .SDRAMW     ( SDRAMW       ),
`ifdef JTFRAME_HEADER
    .HEADER    ( `JTFRAME_HEADER   ),
`endif
`ifdef JTFRAME_BA1_START
    .BA1_START ( BA1_START ),
`endif
`ifdef JTFRAME_BA2_START
    .BA2_START ( BA2_START ),
`endif
`ifdef JTFRAME_BA3_START
    .BA3_START ( BA3_START ),
`endif
`ifdef JTFRAME_PROM_START
    .PROM_START( PROM_START ),
`endif
    .SWAB      ( 1),
    .GFX8B0    ( 0),
    .GFX16B0   ( 0)
) u_dwnld(
    .clk          ( clk            ),
    .ioctl_rom    ( ioctl_dwn      ),
    .ioctl_addr   ( dwnld_addr_wide),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .gfx4_en      ( gfx4_en        ),
    .gfx8_en      ( gfx8_en        ),
    .gfx16_en     ( gfx16_en       ),
    .gfx16b_en    ( gfx16b_en      ),
    .gfx16c_en    ( gfx16c_en      ),
    .prog_addr    ( raw_addr       ),
    .prog_data    ( raw_data       ),
    .prog_mask    ( prog_mask      ), // active low
    .prog_we      ( prog_we        ),
    .prog_rd      ( prog_rd        ),
    .prog_ba      ( prog_ba        ),
    .prom_we      ( prom_we        ),
    .header       ( header         ),
    .sdram_ack    ( prog_ack       )
);

jtframe_headerbyte #(.AW(6)) u_pcbid(
    .clk          ( clk            ),
    .header       ( header         ),
    .ioctl_addr   ( ioctl_addr[5:0]),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .dout         ( pcb_id         )
);
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif


jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    // main
    .SLOT0_AW(19),
    .SLOT0_DW(32), 
    // snd
    .SLOT1_AW(18),
    .SLOT1_DW( 8)
`ifdef JTFRAME_BA0_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
) u_bank0(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { main_addr, 1'b0 } ),
    .slot0_dout  ( main_data  ),
    .slot0_cs    ( main_cs    ),
    .slot0_ok    ( main_ok    ),
    
    .slot1_addr  ( snd_addr  ),
    .slot1_dout  ( snd_data  ),
    .slot1_cs    ( snd_cs    ),
    .slot1_ok    ( snd_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[0]  ),
    .sdram_rd    ( ba_rd[0]   ),
    .sdram_addr  ( ba0_addr   ),
    .data_dst    ( ba_dst[0]  ),
    .data_rdy    ( ba_rdy[0]  ),
    .data_read   ( data_read  )
);
assign ba_wr[0] = 0;
assign ba0_din  = 0;
assign ba0_dsn  = 3;
jtframe_rom_1slot #(
    .SDRAMW(SDRAMW-1),
    // srom
    .SLOT0_AW(21),
    .SLOT0_DW(16)
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_DOUBLE(1)
`endif
) u_bank1(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( srom_addr  ),
    .slot0_dout  ( srom_data  ),
    .slot0_cs    ( srom_cs    ),
    .slot0_ok    ( srom_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[1]  ),
    .sdram_rd    ( ba_rd[1]   ),
    .sdram_addr  ( ba1_addr   ),
    .data_dst    ( ba_dst[1]  ),
    .data_rdy    ( ba_rdy[1]  ),
    .data_read   ( data_read  )
);
assign ba_wr[1] = 0;
assign ba1_din  = 0;
assign ba1_dsn  = 3;
jtframe_rom_1slot #(
    .SDRAMW(SDRAMW-1),
    // grom
    .SLOT0_AW(24),
    .SLOT0_DW(16)
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_DOUBLE(1)
`endif
) u_bank2(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( grom_addr  ),
    .slot0_dout  ( grom_data  ),
    .slot0_cs    ( grom_cs    ),
    .slot0_ok    ( grom_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[2]  ),
    .sdram_rd    ( ba_rd[2]   ),
    .sdram_addr  ( ba2_addr   ),
    .data_dst    ( ba_dst[2]  ),
    .data_rdy    ( ba_rdy[2]  ),
    .data_read   ( data_read  )
);
assign ba_wr[2] = 0;
assign ba2_din  = 0;
assign ba2_dsn  = 3;
jtframe_ram1_2slots #(
    .SDRAMW(SDRAMW-1),
    // grm3
    .SLOT0_AW(18),
    .SLOT0_DW(16), 
    // vram
    .SLOT1_AW(20),
    .SLOT1_DW(16)
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_DOUBLE(1)
`endif
) u_bank3(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( grm3_addr  ),
    .slot0_clr   ( 1'b0       ), // only 1'b0 supported in mem.yaml
    .slot0_dout  ( grm3_data  ),
    .slot0_cs    ( grm3_cs    ),
    .slot0_ok    ( grm3_ok    ),
    
    .slot1_addr  ( vram_addr  ),
    .hold_rst    (  hold_rst  ),
    .slot1_wen   ( vram_we    ),
    .slot1_din   ( vram_din   ),
    .slot1_wrmask( vram_dsn   ),
    .slot1_offset( {(SDRAMW-1){1'b0}} ),
    .slot1_dout  ( vram_data  ),
    .slot1_cs    ( vram_cs    ),
    .slot1_ok    ( vram_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[3]  ),
    .sdram_rd    ( ba_rd[3]   ),
    .sdram_addr  ( ba3_addr   ),
    .sdram_wr    ( ba_wr[3]   ),
    .sdram_wrmask( ba3_dsn    ),
    .data_write  ( ba3_din    ),
    .data_dst    ( ba_dst[3]  ),
    .data_rdy    ( ba_rdy[3]  ),
    .data_read   ( data_read  )
);

`ifdef JTFRAME_PROM_START
localparam JTFRAME_PROM_START=`JTFRAME_PROM_START;
`endif



// Clock enable generation
// 25000000 = 48000000*25/48 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(25),.DEN(48),.MFREQ(48000)) u_cen0_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { e020_cen } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 16000000 = 48000000*1/3 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(1),.DEN(3),.MFREQ(48000)) u_cen1_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { es_cen } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 4000000 = 48000000*1/12 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(1),.DEN(12),.MFREQ(48000)) u_cen2_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { snd_cen } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */


assign snd_vu   = 0;
assign snd_peak = 0;

endmodule
