#define _JTFRAME_PAL_LEN 41097
#define _JTFRAME_ARX 4
#define _JTFRAME_DIPBASE 16
#define _SIM_MS 1
#define _JTFRAME_COMMIT ef70dd5
#define _MIST_SPDIF_AUDIO 1
#define _JTFRAME_DEBUG_VPOS 4
#define _JTFRAME_TIMESTAMP 1784914080
#define _MIST_VGA_8BIT 1
#define _MIST_USE_QSPI 1
#define _JTFRAME_180SHIFT 0
#define _JTFRAME_SIGNED_SND 1
#define _JTFRAME_SDRAM_LARGE 1
#define _JTFRAME_COMMIT_DEC 251071957
#define _GAME_ROM_LEN 512
#define _JTFRAME_PXLCLK 8
#define _JTFRAME_RATE 59.76
#define _JTFRAME_LF_SDRAM_BUFFER 1
#define _JTFRAME_BA3_START 0x23D0000
#define _LINT 1
#define _JTFRAME_BUTTONS 6
#define _GAMETOP jtsftm_game_sdram
#define _JTFRAME_NTSC_LEN 50346
#define _MIST 1
#define _JTFRAME_RFSH_N 11'd1
#define _JTFRAME_WIDTH 384
#define _SFTM 
#define _TARGET sidi128
#define _JTFRAME_BA2_START 0x3D0000
#define _MIST_USE_HDMI 1
#define _JTFRAME_MR_FASTIO 0
#define _JTFRAME_CREDITS_PAGES 3
#define _MIST_DUAL_SDRAM 1
#define _JTFRAME_ARY 3
#define _JTFRAME_BA1_START 0x150000
#define _JTFRAME_RFSH_M 11'd1536
#define _JTFRAME_SDRAM_ROTATION 1
#define _JTFRAME_RFSH_WC 11
#define _JTFRAME_HEIGHT 240
#define _JTFRAME_LF_VW 8
#define _MIST_I2S_AUDIO_HDMI 1
#define _JTFRAME_COLORW 5
#define _VERILATOR 1
#define _SIDI128 1
#define _SIMULATION 1
#define _CORENAME SFTM
#define _JTFRAME_NO_ANALOGIZER 
#define _SEPARATOR -;
#define _CORE_OSD 
#define _JTFRAME_SHIFT 0
#define _JTFRAME_DIALEMU_LEFT 5
#define _MIST_I2S_AUDIO 1
#define _JTFRAME_SDRAM_BANKS 1
#define _JTFRAME_NOSTA 1
#define _JTFRAME_PAL 396713490
#define _JTFRAME_LF_HW 9
#define _JTFRAME_NTSC 320292305
#define _JTFRAME_PLL6000 
#define _MIST_NO_DIRECT_UPLOAD 1
#define _DATE 260724
#define _JTFRAME_MEMGEN 
const bool JTFRAME_CLK48 = false;
const bool JTFRAME_SDRAM96 = false;
const bool JTFRAME_CLK24 = false;
